In [9]:
import torch
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
vector = torch.tensor([1,2,3,4,5,6])
vector

tensor([1, 2, 3, 4, 5, 6])

In [11]:
scalar.ndim , vector.ndim , scalar.shape , vector.shape

(0, 1, torch.Size([]), torch.Size([6]))

In [12]:
scalar.item()

7

In [13]:
tensor = torch.rand(size=(2,3,3))
tensor

tensor([[[0.3793, 0.6355, 0.1580],
         [0.1999, 0.4503, 0.7439],
         [0.5712, 0.9710, 0.4063]],

        [[0.1068, 0.1951, 0.4604],
         [0.7324, 0.5695, 0.3429],
         [0.9300, 0.4550, 0.6739]]])

In [14]:
tensor.shape , tensor.ndim

(torch.Size([2, 3, 3]), 3)

In [15]:
import numpy as np
image = torch.tensor(data=np.random.random(size=(255,255,3)))

In [16]:
import cv2
cv2.imshow(mat=image.numpy(),winname="image")
cv2.waitKey(0)
cv2.destroyAllWindows()

QFontDatabase: Cannot find font directory /home/kartik-agarwal/Documents/PytorchDemo/.venv/lib/python3.10/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/kartik-agarwal/Documents/PytorchDemo/.venv/lib/python3.10/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/kartik-agarwal/Documents/PytorchDemo/.venv/lib/python3.10/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/kartik-agarwal/Documents/PytorchDemo/.venv/lib/python3.10/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for ex

In [17]:
image.dtype , image.shape

(torch.float64, torch.Size([255, 255, 3]))

In [18]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [19]:
image1 = torch.ones_like(image)
image2 = torch.zeros_like(image)
images = torch.cat([image2,image1,image,image1,image2],dim=0)
print(images.device)
cv2.imshow(winname="image",mat=images.numpy())
cv2.waitKey(0)
cv2.destroyAllWindows()

cpu


In [20]:
float_32_tensor = torch.tensor([3.0,6.0,8.0], dtype=torch.float32, device="cuda" , requires_grad=True)

In [30]:
tensor1 = torch.tensor([[1,2],[3,4],[5,6]])
tensor1+10

tensor([[11, 12],
        [13, 14],
        [15, 16]])

In [31]:
tensor1*10

tensor([[10, 20],
        [30, 40],
        [50, 60]])

In [33]:
torch.mul(tensor1,tensor1) , tensor1

(tensor([[ 1,  4],
         [ 9, 16],
         [25, 36]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [37]:
torch.matmul(tensor1,tensor1.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [38]:
tensor1.shape

torch.Size([3, 2])

In [40]:
tensor1 @ tensor1.T

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [67]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
linear2 = torch.nn.Linear(in_features=6, out_features=2)
linear3 = torch.nn.Linear(in_features=2, out_features=10)
x = tensor1.float()


In [68]:
x.dtype

torch.float32

In [69]:
output = linear(x)
output = linear2(output)
output = linear3(output)
output , output.shape , x.shape

(tensor([[-0.6454, -0.2714, -0.8246,  0.7192,  0.6159, -1.1120,  1.2071, -0.6503,
           0.9121, -0.1255],
         [-0.8050, -0.9511, -1.6974,  1.0646,  0.9176, -2.0697,  1.6975, -0.8288,
           1.5876,  0.2669],
         [-0.9645, -1.6308, -2.5702,  1.4099,  1.2194, -3.0274,  2.1878, -1.0073,
           2.2631,  0.6593]], grad_fn=<AddmmBackward0>),
 torch.Size([3, 10]),
 torch.Size([3, 2]))

In [74]:
for i in output:
    print("==========================")
    print(i.max(), "\n" , i.min(), "\n" , i.mean(), "\n" , i.std(), "\n", i.argmax(), "\n", i.argmin())

tensor(1.2071, grad_fn=<MaxBackward1>) 
 tensor(-1.1120, grad_fn=<MinBackward1>) 
 tensor(-0.0175, grad_fn=<MeanBackward0>) 
 tensor(0.8184, grad_fn=<StdBackward0>) 
 tensor(6) 
 tensor(5)
tensor(1.6975, grad_fn=<MaxBackward1>) 
 tensor(-2.0697, grad_fn=<MinBackward1>) 
 tensor(-0.0818, grad_fn=<MeanBackward0>) 
 tensor(1.3657, grad_fn=<StdBackward0>) 
 tensor(6) 
 tensor(5)
tensor(2.2631, grad_fn=<MaxBackward1>) 
 tensor(-3.0274, grad_fn=<MinBackward1>) 
 tensor(-0.1461, grad_fn=<MeanBackward0>) 
 tensor(1.9431, grad_fn=<StdBackward0>) 
 tensor(8) 
 tensor(5)


In [75]:
output.dtype

torch.float32

In [76]:
output = output.type(torch.int64)

In [77]:
output.dtype

torch.int64

In [78]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [79]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [80]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [82]:
output.shape

torch.Size([3, 10])

In [84]:
output[0,5:]

tensor([-1,  1,  0,  0,  0])

In [85]:
a = np.arange(1,8)
tensor1 = torch.from_numpy(a)
tensor1

tensor([1, 2, 3, 4, 5, 6, 7])

In [86]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])